services:
  backend:
    image: ${BACKEND_IMAGE}
    container_name: hydroponic-backend
    restart: unless-stopped
    ports:
      - "5000:5000"

  frontend:
    image: ${FRONTEND_IMAGE}
    container_name: hydroponic-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "80:80"
